name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install lint/test runners
        run: |
          python -m pip install --upgrade pip
          pip install ruff flake8 pytest
      - name: Install project dependencies (non-blocking)
        run: |
          pip install -r config/requirements.txt || true
      - name: Lint (ruff)
        run: ruff check . || true
      - name: Lint (flake8)
        run: flake8 . || true
      - name: Run tests
        run: pytest -q || true
